import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
    ClerkProvider,
    SignInButton,
    SignedIn,
    SignedOut,
    UserButton,
} from "@clerk/nextjs";
import { frFR } from "@clerk/localizations";
import "./globals.css";
import LeftSidebar from "@/components/layout/LeftSideBar";
import TopBar from "@/components/layout/TopBar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider localization={frFR}>
            <html lang="fr">
                <body className={`${inter.className} flex flex-col `}>
                    <TopBar />
                    <main className="flex flex-row pt-16">
                        <SignedIn>
                            <LeftSidebar />
                        </SignedIn>

                        <section className="main-container w-full p-8">
                            <div className="w-full">
                                {children}
                                <Toaster />
                            </div>
                        </section>
                    </main>
                </body>
            </html>
        </ClerkProvider>
    );
}
