import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
    ClerkProvider,
    SignInButton,
    SignedIn,
    SignedOut,
    UserButton,
} from "@clerk/nextjs";
import { frFR } from "@clerk/localizations";
import "./globals.css";
import LeftSidebar from "@/components/layout/LeftSideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider localization={frFR}>
            <html lang="fr">
                <body className={inter.className}>
                    <header>
                        {/* <SignedOut>
                            <SignInButton />
                        </SignedOut> */}
                        <SignedIn>
                            <UserButton />
                        </SignedIn>
                    </header>
                    <main className="flex flex-row">
                        <SignedIn>
                            <LeftSidebar />
                        </SignedIn>

                        <section className="main-container">
                            <div className="w-full max-w-4xl">{children}</div>
                        </section>
                    </main>
                </body>
            </html>
        </ClerkProvider>
    );
}
