import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
    ClerkProvider,
    SignInButton,
    SignedIn,
    SignedOut,
    UserButton,
} from "@clerk/nextjs";
import { frFR } from "@clerk/localizations";
import "./globals.css";
import LeftSidebar from "@/components/layout/LeftSideBar";
import AlertMessage from "@/components/layout/AlertMessage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider localization={frFR}>
            <html lang="fr">
                <body className={`${inter.className}`}>
                    <AlertMessage />
                    <main className="flex flex-row">
                        <SignedIn>
                            <LeftSidebar />
                        </SignedIn>

                        <section className="main-container max-w-3xl w-5/6">
                            <div className="w-full">{children}</div>
                        </section>
                    </main>
                </body>
            </html>
        </ClerkProvider>
    );
}
